name: Email Sender

on:
  schedule:
    - cron: "0 0 */3 * *"  # 每周一0点执行一次
  workflow_dispatch:  # 支持手动触发

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # 可根据需要调整为具体的版本

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run email sender script
      env:
        EMAIL_CONFIG: ${{ secrets.EMAIL_CONFIG }}
        TG_ID: ${{ secrets.TG_ID }}
        TG_TOKEN: ${{ secrets.TG_TOKEN }}
      run: |
        python send_email.py
